const baseOutputSettings = {
  fontStyle: 'Inter',
  fontSize: 48,
  fontColor: '#FFFFFF',
  bold: false,
  italic: false,
  underline: false,
  allCaps: false,
  borderSize: 0,
  borderColor: '#000000',
  dropShadowColor: '#000000',
  dropShadowOpacity: 5,
  dropShadowOffsetX: 0,
  dropShadowOffsetY: 8,
  dropShadowBlur: 10,
  backgroundColor: '#000000',
  backgroundOpacity: 0,
  backgroundBandHeightMode: 'adaptive',
  backgroundBandCustomLines: 3,
  backgroundBandVerticalPadding: 20,
  backgroundBandLockedToMaxLines: false,
  lyricsPosition: 'lower',
  transitionAnimation: 'fade',
  transitionSpeed: 150,
  xMargin: 0,
  yMargin: 0,
  maxLinesEnabled: false,
  maxLines: 3,
  minFontSize: 24,
  translationFontSizeMode: 'bound',
  translationFontSize: 48,
  translationLineColor: '#FBBF24',
  fullScreenMode: false,
  fullScreenBackgroundType: 'color',
  fullScreenBackgroundColor: '#000000',
  fullScreenBackgroundMedia: null,
  fullScreenBackgroundMediaName: '',
  fullScreenRestorePosition: null,
};

export const outputTemplates = [
  {
    id: 'default',
    title: 'Default',
    description: 'Reset to default application settings with standard configuration',
    settings: { ...baseOutputSettings }
  },
  {
    id: 'modern-minimal',
    title: 'Modern Minimal',
    description: 'Clean, contemporary look with subtle shadows and centered text',
    settings: {
      ...baseOutputSettings,
      fontSize: 56,
      dropShadowOpacity: 6,
      transitionSpeed: 300,
    }
  },
  {
    id: 'bold-impact',
    title: 'Bold Impact',
    description: 'High contrast with thick borders and uppercase text for maximum visibility',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Bebas Neue',
      fontSize: 64,
      bold: true,
      allCaps: true,
      borderSize: 4,
      dropShadowOpacity: 8,
      dropShadowOffsetY: 10,
      dropShadowBlur: 15,
      lyricsPosition: 'center',
      transitionAnimation: 'scale',
      transitionSpeed: 250,
    }
  },
  {
    id: 'soft-elegant',
    title: 'Soft & Elegant',
    description: 'Gentle serif font with light shadows, perfect for worship settings',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Lato',
      fontSize: 52,
      fontColor: '#F5F5F5',
      italic: true,
      dropShadowOpacity: 4,
      dropShadowOffsetY: 6,
      dropShadowBlur: 12,
      backgroundColor: '#1A1A1A',
      backgroundOpacity: 3,
      transitionSpeed: 400,
    }
  },
  {
    id: 'classic-karaoke',
    title: 'Classic Karaoke',
    description: 'Traditional karaoke style with full screen and centered positioning',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Arial',
      fontColor: '#FFFF00',
      bold: true,
      borderSize: 3,
      dropShadowOpacity: 7,
      dropShadowOffsetX: 2,
      dropShadowOffsetY: 2,
      dropShadowBlur: 8,
      lyricsPosition: 'center',
      transitionAnimation: 'slide',
      transitionSpeed: 200,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 32,
      fullScreenMode: true,
      fullScreenBackgroundType: 'color',
      fullScreenBackgroundColor: '#000000',
      fullScreenRestorePosition: 'lower',
    }
  },
  {
    id: 'hymn-display',
    title: 'Hymn Display',
    description: 'Traditional hymn presentation with elegant background and centered text',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Lato',
      fontSize: 52,
      dropShadowOpacity: 8,
      dropShadowOffsetY: 10,
      dropShadowBlur: 15,
      lyricsPosition: 'center',
      transitionSpeed: 400,
      maxLinesEnabled: true,
      maxLines: 4,
      minFontSize: 36,
      fullScreenMode: true,
      fullScreenBackgroundType: 'media',
      fullScreenBackgroundColor: '#1A1A2E',
      fullScreenBackgroundMedia: {
        url: '/backgrounds/hymn-texture.jpg',
        mimeType: 'image/jpeg',
        name: 'hymn-texture.jpg',
        size: 0,
        uploadedAt: Date.now(),
        bundled: true,
      },
      fullScreenBackgroundMediaName: 'Hymn Texture Background',
      fullScreenRestorePosition: 'lower',
    }
  },
  {
    id: 'high-contrast',
    title: 'High Contrast',
    description: 'Maximum readability with strong borders and dark background band',
    settings: {
      ...baseOutputSettings,
      fontStyle: 'Roboto',
      fontSize: 58,
      bold: true,
      borderSize: 5,
      dropShadowOpacity: 9,
      dropShadowOffsetY: 12,
      dropShadowBlur: 18,
      backgroundOpacity: 8,
      backgroundBandHeightMode: 'custom',
      backgroundBandCustomLines: 3,
      backgroundBandVerticalPadding: 30,
      transitionSpeed: 200,
      maxLinesEnabled: true,
      maxLines: 3,
      minFontSize: 36,
    }
  },
];

const baseStageSettings = {
  fontStyle: 'Inter',
  backgroundColor: '#000000',
  liveFontSize: 72,
  liveColor: '#FFFFFF',
  liveBold: true,
  liveItalic: false,
  liveUnderline: false,
  liveAllCaps: false,
  liveAlign: 'center',
  nextFontSize: 48,
  nextColor: '#A0A0A0',
  nextBold: false,
  nextItalic: false,
  nextUnderline: false,
  nextAllCaps: false,
  nextAlign: 'center',
  showNextArrow: true,
  nextArrowColor: '#4ADE80',
  prevFontSize: 36,
  prevColor: '#606060',
  prevBold: false,
  prevItalic: false,
  prevUnderline: false,
  prevAllCaps: false,
  prevAlign: 'center',
  currentSongSize: 24,
  currentSongColor: '#FFFFFF',
  upcomingSongSize: 20,
  upcomingSongColor: '#A0A0A0',
  upcomingSongMode: 'automatic',
  upcomingSongFullScreen: false,
  showTime: true,
  bottomBarSize: 18,
  bottomBarColor: '#FFFFFF',
  timerFullScreen: false,
  transitionAnimation: 'fade',
  transitionSpeed: 200,
  translationLineColor: '#FBBF24',
  messageScrollSpeed: 3000,
  customMessagesFullScreen: false,
  maxLinesEnabled: false,
  maxLines: 3,
  minFontSize: 24,
};

export const stageTemplates = [
  {
    id: 'default',
    title: 'Default',
    description: 'Reset to default stage display settings with standard configuration',
    settings: { ...baseStageSettings }
  },
  {
    id: 'stage-classic',
    title: 'Classic Stage',
    description: 'Traditional three-line display with clear current/next/previous distinction',
    settings: { ...baseStageSettings }
  },
  {
    id: 'stage-minimal',
    title: 'Minimal Focus',
    description: 'Emphasizes current line with minimal distractions, subtle next line preview',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Lato',
      backgroundColor: '#0A0A0A',
      liveFontSize: 84,
      nextFontSize: 40,
      nextColor: '#707070',
      nextItalic: true,
      showNextArrow: false,
      prevFontSize: 32,
      prevColor: '#404040',
      currentSongSize: 20,
      currentSongColor: '#E0E0E0',
      upcomingSongSize: 18,
      upcomingSongColor: '#808080',
      showTime: false,
      bottomBarSize: 16,
      bottomBarColor: '#C0C0C0',
      transitionAnimation: 'slide',
      transitionSpeed: 300,
      messageScrollSpeed: 4000,
    }
  },
  {
    id: 'stage-colorful',
    title: 'Colorful Guide',
    description: 'Color-coded lines for easy tracking with vibrant next-line indicator',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Poppins',
      backgroundColor: '#1A1A2E',
      liveFontSize: 68,
      liveColor: '#60A5FA',
      nextFontSize: 52,
      nextColor: '#34D399',
      nextArrowColor: '#10B981',
      prevFontSize: 38,
      prevColor: '#9CA3AF',
      currentSongSize: 22,
      currentSongColor: '#F3F4F6',
      upcomingSongSize: 20,
      upcomingSongColor: '#D1D5DB',
      bottomBarSize: 18,
      bottomBarColor: '#E5E7EB',
      transitionSpeed: 250,
      messageScrollSpeed: 3500,
    }
  },
  {
    id: 'stage-large-text',
    title: 'Large Text',
    description: 'Extra large fonts for visibility from distance, ideal for large stages',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Roboto',
      liveFontSize: 96,
      liveAllCaps: true,
      nextFontSize: 56,
      nextColor: '#B0B0B0',
      nextArrowColor: '#22C55E',
      prevFontSize: 40,
      prevColor: '#707070',
      currentSongSize: 28,
      upcomingSongSize: 24,
      upcomingSongColor: '#B0B0B0',
      bottomBarSize: 20,
      transitionSpeed: 150,
      messageScrollSpeed: 2500,
    }
  },
  {
    id: 'stage-compact',
    title: 'Compact View',
    description: 'Balanced sizing for smaller stages or confidence monitors',
    settings: {
      ...baseStageSettings,
      fontStyle: 'Open Sans',
      backgroundColor: '#121212',
      liveFontSize: 60,
      nextFontSize: 44,
      nextColor: '#9CA3AF',
      nextArrowColor: '#3B82F6',
      prevFontSize: 36,
      prevColor: '#6B7280',
      currentSongSize: 20,
      currentSongColor: '#F9FAFB',
      upcomingSongSize: 18,
      upcomingSongColor: '#9CA3AF',
      bottomBarSize: 16,
      bottomBarColor: '#D1D5DB',
      transitionAnimation: 'slide',
    }
  },
];