/**
 * Output Settings Templates
 * Predefined configurations for Output 1 and Output 2
 */

export const outputTemplates = [
  {
    id: 'default',
    title: 'Default',
    description: 'Reset to default application settings with standard configuration',
    settings: {
      fontStyle: 'Inter',
      fontSize: 48,
      fontColor: '#FFFFFF',
      bold: false,
      italic: false,
      underline: false,
      allCaps: false,
      borderSize: 0,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 5,
      dropShadowOffsetX: 0,
      dropShadowOffsetY: 8,
      dropShadowBlur: 10,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      backgroundBandHeightMode: 'adaptive',
      backgroundBandVerticalPadding: 20,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 150,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: false,
      maxLines: 3,
      minFontSize: 24,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
      fullScreenMode: false,
      fullScreenBackgroundType: 'color',
      fullScreenBackgroundColor: '#000000',
      fullScreenBackgroundMedia: null,
      fullScreenBackgroundMediaName: '',
    }
  },
  {
    id: 'modern-minimal',
    title: 'Modern Minimal',
    description: 'Clean, contemporary look with subtle shadows and centered text',
    settings: {
      fontStyle: 'Inter',
      fontSize: 56,
      fontColor: '#FFFFFF',
      bold: false,
      italic: false,
      underline: false,
      allCaps: false,
      borderSize: 0,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 6,
      dropShadowOffsetX: 0,
      dropShadowOffsetY: 8,
      dropShadowBlur: 10,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 300,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: false,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
    }
  },
  {
    id: 'bold-impact',
    title: 'Bold Impact',
    description: 'High contrast with thick borders and uppercase text for maximum visibility',
    settings: {
      fontStyle: 'Bebas Neue',
      fontSize: 64,
      fontColor: '#FFFFFF',
      bold: true,
      italic: false,
      underline: false,
      allCaps: true,
      borderSize: 4,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 8,
      dropShadowOffsetX: 0,
      dropShadowOffsetY: 10,
      dropShadowBlur: 15,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      lyricsPosition: 'center',
      transitionAnimation: 'scale',
      transitionSpeed: 250,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: false,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
    }
  },
  {
    id: 'soft-elegant',
    title: 'Soft & Elegant',
    description: 'Gentle serif font with light shadows, perfect for worship settings',
    settings: {
      fontStyle: 'Lato',
      fontSize: 52,
      fontColor: '#F5F5F5',
      bold: false,
      italic: true,
      underline: false,
      allCaps: false,
      borderSize: 0,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 4,
      dropShadowOffsetX: 0,
      dropShadowOffsetY: 6,
      dropShadowBlur: 12,
      backgroundColor: '#1A1A1A',
      backgroundOpacity: 3,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 400,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: false,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
    }
  },
  {
    id: 'classic-karaoke',
    title: 'Classic Karaoke',
    description: 'Traditional karaoke style with full screen and centered positioning',
    settings: {
      fontStyle: 'Arial',
      fontSize: 48,
      fontColor: '#FFFF00',
      bold: true,
      italic: false,
      underline: false,
      allCaps: false,
      borderSize: 3,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 7,
      dropShadowOffsetX: 2,
      dropShadowOffsetY: 2,
      dropShadowBlur: 8,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      backgroundBandHeightMode: 'adaptive',
      backgroundBandVerticalPadding: 20,
      lyricsPosition: 'center',
      transitionAnimation: 'slide',
      transitionSpeed: 200,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: true,
      maxLines: 2,
      minFontSize: 32,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
      fullScreenMode: true,
      fullScreenBackgroundType: 'color',
      fullScreenBackgroundColor: '#000000',
      fullScreenRestorePosition: 'lower',
    }
  },
  {
    id: 'hymn-display',
    title: 'Hymn Display',
    description: 'Traditional hymn presentation with elegant background and centered text',
    settings: {
      fontStyle: 'Lato',
      fontSize: 52,
      fontColor: '#FFFFFF',
      bold: false,
      italic: false,
      underline: false,
      allCaps: false,
      borderSize: 0,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 8,
      dropShadowOffsetX: 0,
      dropShadowOffsetY: 10,
      dropShadowBlur: 15,
      backgroundColor: '#000000',
      backgroundOpacity: 0,
      backgroundBandHeightMode: 'adaptive',
      backgroundBandVerticalPadding: 20,
      lyricsPosition: 'center',
      transitionAnimation: 'fade',
      transitionSpeed: 400,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: true,
      maxLines: 4,
      minFontSize: 36,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
      fullScreenMode: true,
      fullScreenBackgroundType: 'media',
      fullScreenBackgroundColor: '#1A1A2E',
      fullScreenBackgroundMedia: {
        url: '/backgrounds/hymn-texture.jpg',
        mimeType: 'image/jpeg',
        name: 'hymn-texture.jpg',
        size: 0,
        uploadedAt: Date.now(),
        bundled: true, // Flag to indicate this is a bundled asset
      },
      fullScreenBackgroundMediaName: 'Hymn Texture Background',
      fullScreenRestorePosition: 'lower',
    }
  },
  {
    id: 'high-contrast',
    title: 'High Contrast',
    description: 'Maximum readability with strong borders and dark background band',
    settings: {
      fontStyle: 'Roboto',
      fontSize: 58,
      fontColor: '#FFFFFF',
      bold: true,
      italic: false,
      underline: false,
      allCaps: false,
      borderSize: 5,
      borderColor: '#000000',
      dropShadowColor: '#000000',
      dropShadowOpacity: 9,
      dropShadowOffsetX: 0,
      dropShadowOffsetY: 12,
      dropShadowBlur: 18,
      backgroundColor: '#000000',
      backgroundOpacity: 8,
      backgroundBandHeightMode: 'custom',
      backgroundBandCustomLines: 3,
      backgroundBandVerticalPadding: 30,
      lyricsPosition: 'lower',
      transitionAnimation: 'fade',
      transitionSpeed: 200,
      xMargin: 0,
      yMargin: 0,
      maxLinesEnabled: true,
      maxLines: 3,
      minFontSize: 36,
      translationFontSizeMode: 'bound',
      translationLineColor: '#FBBF24',
    }
  },
];

/**
 * Stage Display Templates
 * Predefined configurations for Stage display
 */
export const stageTemplates = [
  {
    id: 'default',
    title: 'Default',
    description: 'Reset to default stage display settings with standard configuration',
    settings: {
      fontStyle: 'Inter',
      backgroundColor: '#000000',
      // Live line
      liveFontSize: 72,
      liveColor: '#FFFFFF',
      liveBold: true,
      liveItalic: false,
      liveUnderline: false,
      liveAllCaps: false,
      liveAlign: 'center',
      // Next line
      nextFontSize: 48,
      nextColor: '#A0A0A0',
      nextBold: false,
      nextItalic: false,
      nextUnderline: false,
      nextAllCaps: false,
      nextAlign: 'center',
      showNextArrow: true,
      nextArrowColor: '#4ADE80',
      // Previous line
      prevFontSize: 36,
      prevColor: '#606060',
      prevBold: false,
      prevItalic: false,
      prevUnderline: false,
      prevAllCaps: false,
      prevAlign: 'center',
      // Top bar
      currentSongSize: 24,
      currentSongColor: '#FFFFFF',
      upcomingSongSize: 20,
      upcomingSongColor: '#A0A0A0',
      upcomingSongMode: 'automatic',
      upcomingSongFullScreen: false,
      // Bottom bar
      showTime: true,
      bottomBarSize: 18,
      bottomBarColor: '#FFFFFF',
      timerFullScreen: false,
      // Transition
      transitionAnimation: 'fade',
      transitionSpeed: 200,
      // Translation
      translationLineColor: '#FBBF24',
      // Messages
      messageScrollSpeed: 3000,
      customMessagesFullScreen: false,
    }
  },
  {
    id: 'stage-classic',
    title: 'Classic Stage',
    description: 'Traditional three-line display with clear current/next/previous distinction',
    settings: {
      fontStyle: 'Inter',
      backgroundColor: '#000000',
      // Live line
      liveFontSize: 72,
      liveColor: '#FFFFFF',
      liveBold: true,
      liveItalic: false,
      liveUnderline: false,
      liveAllCaps: false,
      liveAlign: 'center',
      // Next line
      nextFontSize: 48,
      nextColor: '#A0A0A0',
      nextBold: false,
      nextItalic: false,
      nextUnderline: false,
      nextAllCaps: false,
      nextAlign: 'center',
      showNextArrow: true,
      nextArrowColor: '#4ADE80',
      // Previous line
      prevFontSize: 36,
      prevColor: '#606060',
      prevBold: false,
      prevItalic: false,
      prevUnderline: false,
      prevAllCaps: false,
      prevAlign: 'center',
      // Top bar
      currentSongSize: 24,
      currentSongColor: '#FFFFFF',
      upcomingSongSize: 20,
      upcomingSongColor: '#A0A0A0',
      upcomingSongMode: 'automatic',
      // Bottom bar
      showTime: true,
      bottomBarSize: 18,
      bottomBarColor: '#FFFFFF',
      // Transition
      transitionAnimation: 'fade',
      transitionSpeed: 200,
      // Translation
      translationLineColor: '#FBBF24',
      // Messages
      messageScrollSpeed: 3000,
    }
  },
  {
    id: 'stage-minimal',
    title: 'Minimal Focus',
    description: 'Emphasizes current line with minimal distractions, subtle next line preview',
    settings: {
      fontStyle: 'Lato',
      backgroundColor: '#0A0A0A',
      // Live line
      liveFontSize: 84,
      liveColor: '#FFFFFF',
      liveBold: true,
      liveItalic: false,
      liveUnderline: false,
      liveAllCaps: false,
      liveAlign: 'center',
      // Next line
      nextFontSize: 40,
      nextColor: '#707070',
      nextBold: false,
      nextItalic: true,
      nextUnderline: false,
      nextAllCaps: false,
      nextAlign: 'center',
      showNextArrow: false,
      nextArrowColor: '#4ADE80',
      // Previous line
      prevFontSize: 32,
      prevColor: '#404040',
      prevBold: false,
      prevItalic: false,
      prevUnderline: false,
      prevAllCaps: false,
      prevAlign: 'center',
      // Top bar
      currentSongSize: 20,
      currentSongColor: '#E0E0E0',
      upcomingSongSize: 18,
      upcomingSongColor: '#808080',
      upcomingSongMode: 'automatic',
      // Bottom bar
      showTime: false,
      bottomBarSize: 16,
      bottomBarColor: '#C0C0C0',
      // Transition
      transitionAnimation: 'slide',
      transitionSpeed: 300,
      // Translation
      translationLineColor: '#FBBF24',
      // Messages
      messageScrollSpeed: 4000,
    }
  },
  {
    id: 'stage-colorful',
    title: 'Colorful Guide',
    description: 'Color-coded lines for easy tracking with vibrant next-line indicator',
    settings: {
      fontStyle: 'Poppins',
      backgroundColor: '#1A1A2E',
      // Live line
      liveFontSize: 68,
      liveColor: '#60A5FA',
      liveBold: true,
      liveItalic: false,
      liveUnderline: false,
      liveAllCaps: false,
      liveAlign: 'center',
      // Next line
      nextFontSize: 52,
      nextColor: '#34D399',
      nextBold: false,
      nextItalic: false,
      nextUnderline: false,
      nextAllCaps: false,
      nextAlign: 'center',
      showNextArrow: true,
      nextArrowColor: '#10B981',
      // Previous line
      prevFontSize: 38,
      prevColor: '#9CA3AF',
      prevBold: false,
      prevItalic: false,
      prevUnderline: false,
      prevAllCaps: false,
      prevAlign: 'center',
      // Top bar
      currentSongSize: 22,
      currentSongColor: '#F3F4F6',
      upcomingSongSize: 20,
      upcomingSongColor: '#D1D5DB',
      upcomingSongMode: 'automatic',
      // Bottom bar
      showTime: true,
      bottomBarSize: 18,
      bottomBarColor: '#E5E7EB',
      // Transition
      transitionAnimation: 'fade',
      transitionSpeed: 250,
      // Translation
      translationLineColor: '#FBBF24',
      // Messages
      messageScrollSpeed: 3500,
    }
  },
  {
    id: 'stage-large-text',
    title: 'Large Text',
    description: 'Extra large fonts for visibility from distance, ideal for large stages',
    settings: {
      fontStyle: 'Roboto',
      backgroundColor: '#000000',
      // Live line
      liveFontSize: 96,
      liveColor: '#FFFFFF',
      liveBold: true,
      liveItalic: false,
      liveUnderline: false,
      liveAllCaps: true,
      liveAlign: 'center',
      // Next line
      nextFontSize: 56,
      nextColor: '#B0B0B0',
      nextBold: false,
      nextItalic: false,
      nextUnderline: false,
      nextAllCaps: false,
      nextAlign: 'center',
      showNextArrow: true,
      nextArrowColor: '#22C55E',
      // Previous line
      prevFontSize: 40,
      prevColor: '#707070',
      prevBold: false,
      prevItalic: false,
      prevUnderline: false,
      prevAllCaps: false,
      prevAlign: 'center',
      // Top bar
      currentSongSize: 28,
      currentSongColor: '#FFFFFF',
      upcomingSongSize: 24,
      upcomingSongColor: '#B0B0B0',
      upcomingSongMode: 'automatic',
      // Bottom bar
      showTime: true,
      bottomBarSize: 20,
      bottomBarColor: '#FFFFFF',
      // Transition
      transitionAnimation: 'fade',
      transitionSpeed: 150,
      // Translation
      translationLineColor: '#FBBF24',
      // Messages
      messageScrollSpeed: 2500,
    }
  },
  {
    id: 'stage-compact',
    title: 'Compact View',
    description: 'Balanced sizing for smaller stages or confidence monitors',
    settings: {
      fontStyle: 'Open Sans',
      backgroundColor: '#121212',
      // Live line
      liveFontSize: 60,
      liveColor: '#FFFFFF',
      liveBold: true,
      liveItalic: false,
      liveUnderline: false,
      liveAllCaps: false,
      liveAlign: 'center',
      // Next line
      nextFontSize: 44,
      nextColor: '#9CA3AF',
      nextBold: false,
      nextItalic: false,
      nextUnderline: false,
      nextAllCaps: false,
      nextAlign: 'center',
      showNextArrow: true,
      nextArrowColor: '#3B82F6',
      // Previous line
      prevFontSize: 36,
      prevColor: '#6B7280',
      prevBold: false,
      prevItalic: false,
      prevUnderline: false,
      prevAllCaps: false,
      prevAlign: 'center',
      // Top bar
      currentSongSize: 20,
      currentSongColor: '#F9FAFB',
      upcomingSongSize: 18,
      upcomingSongColor: '#9CA3AF',
      upcomingSongMode: 'automatic',
      // Bottom bar
      showTime: true,
      bottomBarSize: 16,
      bottomBarColor: '#D1D5DB',
      // Transition
      transitionAnimation: 'slide',
      transitionSpeed: 200,
      // Translation
      translationLineColor: '#FBBF24',
      // Messages
      messageScrollSpeed: 3000,
    }
  },
];
